from enum import StrEnum

class DeskState(StrEnum):
    FREE="FREE"
    DISCOVER="DISCOVER"
    SNAPSHOT="SNAPSHOT"
    FILTER="FILTER"
    JUDGE="JUDGE"
    VALIDATE="VALIDATE"
    SELECT="SELECT"
    SHADOW_SIZE="SHADOW_SIZE"
    SHADOW_ENTRY="SHADOW_ENTRY"
    MONITOR="MONITOR"
    SHADOW_EXIT="SHADOW_EXIT"
    OUTCOME="OUTCOME"
    REPLAY="REPLAY"
    RECONCILE="RECONCILE"
    FAILED="FAILED"
